# Generated by Django 6.1 on 2026-09-12 16:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=255)),
                ('degree', models.CharField(choices=[('elementary', 'Elementary School'), ('junior_high', 'Junior High School'), ('high_school', 'High School'), ('bachelor', 'Bachelor Degree'), ('master', 'Master Degree'), ('doctoral', 'Doctoral Degree')], default='bachelor', max_length=50)),
                ('field_of_study', models.CharField(max_length=255)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
